version: '3'

services:
  web:
    build: 'web'
    ports:
      - '5000:5000'
  api:
    build: 'api'
    ports:
      - '5050:8000' # TODO Retirer l'accès au port et créer un network interne
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' # Accès à l'instance Docker