version: '3'

services:
  web:
    build: 'web'
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URI=mysql+pymysql://root:dbadmin@appdb:3306/mysql_db
    depends_on:
      appdb:
        condition: service_healthy
  api:
    build: 'api'
    ports:
      - '5050:8000' # TODO Retirer l'accès au port et créer un network interne
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' # Accès à l'instance Docker
  appdb:
    build: './db'
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql_db
      - MYSQL_ROOT_PASSWORD=dbadmin
    healthcheck:
      # This is a dummy query. Using a ping or curl will return false positives
      test: mysql -h localhost --user=root --password=dbadmin -e "SELECT 1;"
      interval: 5s
      timeout: 2s
      retries: 20
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysqldata:
