name: Linter

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['api', 'web']
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    name: PyLint on ${{ matrix.folder }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies of ${{ matrix.folder }}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint on ${{ matrix.folder }}
      run: |
        pylint $(find . -name '*.py')
  eof:
    runs-on: ubuntu-latest
    name: All files end with newline
    steps:
      - uses: actions/checkout@v3
      - name: Check all files for newline
        run: git ls-files | xargs -L1 bash -c 'test "$(tail -c1 "$0")" && { echo "No newline at end of $0"; exit 1; } || exit 0'
